name: "Comment to Issue"
description: "Converts IDE TODO/BUG/etc comments to GitHub issues"
author: "Sean Sherman"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "arrow-up-circle"
  color: "green"
inputs:
  REPO:
    description: "The path to the repository where the action will be used, e.g. 'alstr/my-repo' (automatically set)"
    required: true
    default: "${{ github.repository }}"
  BEFORE:
    description: "The SHA of the last pushed commit (automatically set)"
    required: true
    default: "${{ github.event.before || github.base_ref }}"
  COMMITS:
    description: "An array of commit objects describing the pushed commits"
    required: true
    default: "${{ toJSON(github.event.commits) }}"
  DIFF_URL:
    description: "The URL to use to get the diff (automatically set)"
    required: true
    default: "${{ github.event.pull_request.diff_url }}"
  SHA:
    description: "The SHA of the latest commit (automatically set)"
    required: true
    default: "${{ github.sha }}"
  TOKEN:
    description: "The GitHub access token to allow us to retrieve, create and update issues (automatically set)"
    required: false
    default: ${{ github.token }}
  ISSUE_IDENTIFIERS:
    description: "The Tag used to signify that a comment is/to be associated with an issue in Github. Default value is 'TODO', but you can add as many terms as you like, separating each term using the pipe operator. For example: 'TODO|BUG|TESTING'"
    required: false
    default: "TODO"
  CLOSE_ISSUES:
    description: "Optional input that specifies whether to attempt to close an issue when a TODO is removed"
    required: true
    default: true
  AUTO_P:
    description: "For multiline TODOs, format each line as a new paragraph when creating the issue"
    required: true
    default: true
  IGNORE:
    description: "A collection of comma-delimited regular expression that matches files that should be ignored when searching for TODOs"
    required: false
  AUTO_ASSIGN:
    description: "Automatically assign new issues to the user who triggered the action"
    required: true
    default: false
  ACTOR:
    description: "The username of the person who triggered the action"
    required: true
    default: "${{ github.actor }}"
  ISSUE_TEMPLATE:
    description: "The template used to format new issues"
    required: false
